export const data: any = [
  {
    id: "string",
    requestType: "string",
    toolName: "string",
    quantity: "string",
    project: "string",
    pickedOn: "string",
    pickedBy: "string",
    status: "string",
    returnedOn: "string",
  },
  {
    id: "string",
    requestType: "string",
    toolName: "string",
    quantity: "string",
    project: "string",
    pickedOn: "string",
    pickedBy: "string",
    status: "string",
    returnedOn: "string",
  },
  {
    id: "string",
    requestType: "string",
    toolName: "string",
    quantity: "string",
    project: "string",
    pickedOn: "string",
    pickedBy: "string",
    status: "string",
    returnedOn: "string",
  },
  {
    id: "string",
    requestType: "string",
    toolName: "string",
    quantity: "string",
    project: "string",
    pickedOn: "string",
    pickedBy: "string",
    status: "string",
    returnedOn: "string",
  },
];
