export const data: Array<any> = [
  {
    id: "string",
    contractorCode: "string",
    projectCode: "string",
    createdBy: "string",
    amount: "string",
    createdOn: "string",
    service: "string",
    status: "string",
    actions: "string",
  },

  {
    id: "string",
    contractorCode: "string",
    projectCode: "string",
    createdBy: "string",
    amount: "string",
    createdOn: "string",
    service: "string",
    status: "string",
    actions: "string",
  },
  {
    id: "string",
    contractorCode: "string",
    projectCode: "string",
    createdBy: "string",
    amount: "string",
    createdOn: "string",
    service: "string",
    status: "string",
    actions: "string",
  },
  {
    id: "string",
    contractorCode: "string",
    projectCode: "string",
    createdBy: "string",
    amount: "string",
    createdOn: "string",
    service: "string",
    status: "string",
    actions: "string",
  },
  {
    id: "string",
    contractorCode: "string",
    projectCode: "string",
    createdBy: "string",
    amount: "string",
    createdOn: "string",
    service: "string",
    status: "string",
    actions: "string",
  },
];
