export const data: Array<any> = [
  {
    id: "string",
    tenantCode: "string",
    title: "string",
    fullName: "string",
    phoneNumber: "string",
    emailAddress: "string",
    dateAdded: "string",
    status: "string",
    actions: "string",
    actions1: "string",
  },
  {
    id: "string",
    tenantCode: "string",
    title: "string",
    fullName: "string",
    phoneNumber: "string",
    emailAddress: "string",
    dateAdded: "string",
    status: "string",
    actions: "string",
    actions1: "string",
  },
  {
    id: "string",
    tenantCode: "string",
    title: "string",
    fullName: "string",
    phoneNumber: "string",
    emailAddress: "string",
    dateAdded: "string",
    status: "string",
    actions: "string",
    actions1: "string",
  },
  {
    id: "string",
    tenantCode: "string",
    title: "string",
    fullName: "string",
    phoneNumber: "string",
    emailAddress: "string",
    dateAdded: "string",
    status: "string",
    actions: "string",
    actions1: "string",
  },
];
