import { ConsultantsType } from "./columns";

export const data: Array<ConsultantsType> = [
  {
    id: "1",
    fullName: "John Doe",
    type: "Structural Engineer",
    emailAddress: "Xxqz8@example.com",
    contactPhone: "08012345678",
    website: "www.johndoe.com",
    dateAdded: "2022-01-01",
    actions: "https://www.google.com/",
  },
  {
    id: "2",
    fullName: "John Doe",
    type: "Structural Engineer",
    emailAddress: "Xxqz8@example.com",
    contactPhone: "08012345678",
    website: "www.johndoe.com",
    dateAdded: "2022-01-01",
    actions: "https://www.google.com/",
  },
  {
    id: "3",
    fullName: "John Doe",
    type: "Structural Engineer",
    emailAddress: "Xxqz8@example.com",
    contactPhone: "08012345678",
    website: "www.johndoe.com",
    dateAdded: "2022-01-01",
    actions: "https://www.google.com",
  },
  {
    id: "4",
    fullName: "John Doe",
    type: "Structural Engineer",
    emailAddress: "Xxqz8@example.com",
    contactPhone: "08012345678",
    website: "www.johndoe.com",
    dateAdded: "2022-01-01",
    actions: "https://www.google.com/",
  },
  {
    id: "5",
    fullName: "John Doe",
    type: "Structural Engineer",
    emailAddress: "Xxqz8@example.com",
    contactPhone: "08012345678",
    website: "www.johndoe.com",
    dateAdded: "2022-01-01",
    actions: "https://www.google.com/",
  },
];
