export const data = [
  {
    id: "1",
    fullName: "John Doe",
    type: "Structural Engineer",
    emailAddress: "Xxqz8@example.com",
    contactPhone: "08012345678",
    website: "www.johndoe.com",
    dateAdded: "2022-01-01",
    actions: "https://www.google.com/",
  },
  {
    id: "2",
    fullName: "Jane Smith",
    type: "Interior Designer",
    emailAddress: "jane.smith@example.com",
    contactPhone: "09098765432",
    website: "www.janesmithdesigns.com",
    dateAdded: "2022-02-15",
    actions: "https://www.example.com/",
  },
  {
    id: "3",
    fullName: "Alice Johnson",
    type: "Architect",
    emailAddress: "alice.johnson@example.com",
    contactPhone: "07011223344",
    website: "www.alicejohnsonarchitects.com",
    dateAdded: "2022-03-20",
    actions: "https://www.example.com/",
  },
  {
    id: "4",
    fullName: "Robert Brown",
    type: "Construction Manager",
    emailAddress: "rbrown@example.com",
    contactPhone: "08055566677",
    website: "www.robertbrownconstruction.com",
    dateAdded: "2022-04-10",
    actions: "https://www.example.com/",
  },
  {
    id: "5",
    fullName: "Emily Davis",
    type: "Surveyor",
    emailAddress: "emily.davis@example.com",
    contactPhone: "08099988877",
    website: "www.emilydavissurveying.com",
    dateAdded: "2022-05-05",
    actions: "https://www.example.com/",
  },
];
