import { ISupplierData } from "@/utils/types";

export const data: Array<ISupplierData> = [
  {
    id: "1",
    supplier_name: "Supplier 1",
    supplier_address: "Abuja, Nigeria",
    supplier_ofc_phone: "08000000000",
    contact_person: "John Doe",
    contact_home_phone: "08000000000",
    createdAt: "6 July, 2023",
    comment: "",
    contact_mobile: "",
    supplier_code: "",
    updatedAt: "",
  },
  {
    id: "2",
    supplier_name: "Supplier 2",
    supplier_address: "Lagos, Nigeria",
    supplier_ofc_phone: "08011111111",
    contact_person: "Jane Smith",
    contact_home_phone: "08011111111",
    createdAt: "12 September, 2023",
    comment: "",
    contact_mobile: "",
    supplier_code: "",
    updatedAt: "",
  },
  {
    id: "3",
    supplier_name: "Supplier 3",
    supplier_address: "Accra, Ghana",
    supplier_ofc_phone: "0234567890",
    contact_person: "Alice Johnson",
    contact_home_phone: "0234567890",
    createdAt: "3 March, 2023",
    comment: "",
    contact_mobile: "",
    supplier_code: "",
    updatedAt: "",
  },
  {
    id: "4",
    supplier_name: "Supplier 4",
    supplier_address: "Nairobi, Kenya",
    supplier_ofc_phone: "0722000000",
    contact_person: "Robert Brown",
    contact_home_phone: "0722000000",
    createdAt: "19 November, 2023",
    comment: "",
    contact_mobile: "",
    supplier_code: "",
    updatedAt: "",
  },
  // Add more entries as needed
];
