// import { ReportType } from "./columns";

// export const data: Array<ReportType> = [
//   {
//     id: "1",
//     reportTitle: "Report 1",
//     submittedOn: "2022-01-01",
//     reportType: "Type 1",
//     project: "Bode Peters",
//     createdBy: "User 1",
//     createdFor: "User 2",
//     actions: "https://www.google.com",
//   },
//   {
//     id: "1",
//     reportTitle: "Report 1",
//     submittedOn: "2022-01-01",
//     reportType: "Type 1",
//     project: "Bode Peters",
//     createdBy: "User 1",
//     createdFor: "User 2",
//     actions: "https://www.google.com",
//   },
//   {
//     id: "1",
//     reportTitle: "Report 1",
//     submittedOn: "2022-01-01",
//     reportType: "Type 1",
//     project: "Bode Peters",
//     createdBy: "User 1",
//     createdFor: "User 2",
//     actions: "https://www.google.com",
//   },
//   {
//     id: "1",
//     reportTitle: "Report 1",
//     submittedOn: "2022-01-01",
//     reportType: "Type 1",
//     project: "Bode Peters",
//     createdBy: "User 1",
//     createdFor: "User 2",
//     actions: "https://www.google.com",
//   },
//   {
//     id: "1",
//     reportTitle: "Report 1",
//     submittedOn: "2022-01-01",
//     reportType: "Type 1",
//     project: "Bode Peters",
//     createdBy: "User 1",
//     createdFor: "User 2",
//     actions: "https://www.google.com",
//   },
// ];
