import { ReportType } from "./columns";

export const data: Array<ReportType> = [
  {
    id: "string",
    description: "string",
    totalQuantity: "string",
    quantityLeft: "string",
    inventoryCode: "string",
    type: "string",
    addedBy: "string",
    addedOn: "string",
    actions: "string",
  },
  {
    id: "string",
    description: "string",
    totalQuantity: "string",
    quantityLeft: "string",
    inventoryCode: "string",
    type: "string",
    addedBy: "string",
    addedOn: "string",
    actions: "string",
  },
  {
    id: "string",
    description: "string",
    totalQuantity: "string",
    quantityLeft: "string",
    inventoryCode: "string",
    type: "string",
    addedBy: "string",
    addedOn: "string",
    actions: "string",
  },
  {
    id: "string",
    description: "string",
    totalQuantity: "string",
    quantityLeft: "string",
    inventoryCode: "string",
    type: "string",
    addedBy: "string",
    addedOn: "string",
    actions: "string",
  },
  {
    id: "string",
    description: "string",
    totalQuantity: "string",
    quantityLeft: "string",
    inventoryCode: "string",
    type: "string",
    addedBy: "string",
    addedOn: "string",
    actions: "string",
  },
  
];
